//
//   COMPONENT_NAME: somx
//
//   ORIGINS: 27
//
//
//   25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//
//   @(#) 1.3 src/somples.os2/somk/cpp/derived/mello.idl, somk.tst, som3.0 12/13/96 11:27:28 [12/24/96 07:41:07]

/*
 *
 * DISCLAIMER OF WARRANTIES.
 * The following [enclosed] code is sample code created by IBM
 * Corporation. This sample code is not part of any standard or IBM
 * product and is provided to you solely for the purpose of assisting
 * you in the development of your applications.  The code is provided
 * "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 * THIS CODE.  IBM shall not be liable for any damages arising out of
 * your use of the sample code, even if they have been advised of the
 * possibility of such damages.
 *
 * DISTRIBUTION.
 * This sample code can be freely distributed, copied, altered, and
 * incorporated into other software, provided that it bears the above
 * Copyright notice and DISCLAIMER intact.
 */

#ifndef mello_h
#define mello_h

#include <somcls.idl>

interface M_Mello;
interface Mello : SOMObject
{
    string mello_();
    attribute string msg;
#ifdef __SOMIDL__
implementation
{
    releaseorder:  mello_, _get_msg, _set_msg;
    callstyle=oidl;
    filestem = mello;
    metaclass = M_Mello;
    somInit:override;
};
#endif /* __SOMIDL__ */
};

interface M_Mello : SOMClass
{
    Mello MelloCreate(in string msg);
#ifdef __SOMIDL__
implementation
{
   releaseorder: MelloCreate;
   callstyle=oidl;
   filestem = mello;
};
#endif /* __SOMIDL__ */
};

#endif /* mello_h */
