//
//   COMPONENT_NAME: somx
//
//   ORIGINS: 27
//
//
//   25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//
//   @(#) 2.8.1.1 src/somples.os2/somd/c/dii/foo.idl, somples.somd, som3.0 12/2/96 17:45:32 [12/24/96 07:40:52]

/*
 *
 * DISCLAIMER OF WARRANTIES.
 * The following [enclosed] code is sample code created by IBM
 * Corporation. This sample code is not part of any standard or IBM
 * product and is provided to you solely for the purpose of assisting
 * you in the development of your applications.  The code is provided
 * "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 * THIS CODE.  IBM shall not be liable for any damages arising out of
 * your use of the sample code, even if they have been advised of the
 * possibility of such damages.
 *
 * DISTRIBUTION.
 * This sample code can be freely distributed, copied, altered, and
 * incorporated into other software, provided that it bears the above
 * Copyright notice and DISCLAIMER intact.
 */


#ifndef Foo_idl
#define Foo_idl

#include <somobj.idl>
#include <somdtype.idl>

interface Foo : SOMObject
{
  string method1(out string a, inout long b, in ReferenceData c);

#ifdef __SOMIDL__
  implementation {
    releaseorder: method1;
    callstyle = idl;
    dllname = "foo.dll";

    memory_management = corba;

    //# client shouldn't free result or out parameter 'a' of method1:
    method1: object_owns_result;
    method1: object_owns_parameters = "a";
  };
#endif /* __SOMIDL__ */

};
#endif /* Foo_idl */
