/*
 *   COMPONENT_NAME: somx
 *
 *   ORIGINS: 27
 *
 *
 *   25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996  
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

#ifndef lint
static char *sccsid = "@(#) 1.1 src/somples.os2/somu/c/fb/barking.c, somples.somu, som3.0 12/2/96 14:33:02 [12/24/96 07:55:18]";
#endif

/*
 *
 * DISCLAIMER OF WARRANTIES.
 * The following [enclosed] code is sample code created by IBM
 * Corporation. This sample code is not part of any standard or IBM
 * product and is provided to you solely for the purpose of assisting
 * you in the development of your applications.  The code is provided
 * "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 * THIS CODE.  IBM shall not be liable for any damages arising out of
 * your use of the sample code, even if they have been advised of the
 * possibility of such damages.
 *
 * DISTRIBUTION.
 * This sample code can be freely distributed, copied, altered, and
 * incorporated into other software, provided that it bears the above
 * Copyright notice and DISCLAIMER intact.
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.41
 */

#ifndef SOM_Module_barking_Source
#define SOM_Module_barking_Source
#endif

#include <stdio.h>

#define Barking_Class_Source
#include <barking.ih>


SOM_Scope boolean  SOMLINK sommBeforeMethod(Barking somSelf, 
                                             Environment *ev, 
                                            SOMObject object, 
                                            somId methodId, va_list ap)
{
    /* BarkingData *somThis = BarkingGetData(somSelf); */
    BarkingMethodDebug("Barking","sommBeforeMethod");

    printf( "WOOF\n" );
    return (Barking_parent_SOMMBeforeAfter_sommBeforeMethod(somSelf, 
                                                            ev, 
                                                            object, 
                                                            methodId, 
                                                            ap));
}

SOM_Scope void  SOMLINK sommAfterMethod(Barking somSelf,  Environment *ev, 
                                        SOMObject object, somId methodId, 
                                        somToken returnedvalue, 
                                        va_list ap)
{
    /* BarkingData *somThis = BarkingGetData(somSelf); */
    BarkingMethodDebug("Barking","sommAfterMethod");

    printf( "WOOF\n" );
    Barking_parent_SOMMBeforeAfter_sommAfterMethod(somSelf, ev, 
                                                   object, methodId, 
                                                   returnedvalue, 
                                                   ap);
}

