/*
 *   COMPONENT_NAME: somx
 *
 *   ORIGINS: 27
 *
 *
 *   25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

#ifndef lint
static char *sccsid = "@(#) 1.1 src/somples.os2/somu/c/fb/fierce.c, somples.somu, som3.0 12/2/96 14:35:34 [12/24/96 07:55:21]";
#endif

/*
 *
 * DISCLAIMER OF WARRANTIES.
 * The following [enclosed] code is sample code created by IBM
 * Corporation. This sample code is not part of any standard or IBM
 * product and is provided to you solely for the purpose of assisting
 * you in the development of your applications.  The code is provided
 * "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 * THIS CODE.  IBM shall not be liable for any damages arising out of
 * your use of the sample code, even if they have been advised of the
 * possibility of such damages.
 *
 * DISTRIBUTION.
 * This sample code can be freely distributed, copied, altered, and
 * incorporated into other software, provided that it bears the above
 * Copyright notice and DISCLAIMER intact.
 */

/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using: 
 *      SOM Emitter emitctm: 2.41
 */

#ifndef SOM_Module_fierce_Source
#define SOM_Module_fierce_Source
#endif

#include <stdio.h>

#define Fierce_Class_Source
#include <fierce.ih>

SOM_Scope boolean  SOMLINK sommBeforeMethod(Fierce somSelf,  Environment *ev, 
                                            SOMObject object, 
                                            somId methodId, va_list ap)
{
    /* FierceData *somThis = FierceGetData(somSelf); */
    FierceMethodDebug("Fierce","sommBeforeMethod");

    printf( "GRRR\n" );
    return (Fierce_parent_SOMMBeforeAfter_sommBeforeMethod(somSelf, 
                                                           ev, 
                                                           object, 
                                                           methodId, 
                                                           ap));
}

SOM_Scope void  SOMLINK sommAfterMethod(Fierce somSelf,  Environment *ev, 
                                        SOMObject object, somId methodId, 
                                        somToken returnedvalue, 
                                        va_list ap)
{
    /* FierceData *somThis = FierceGetData(somSelf); */
    FierceMethodDebug("Fierce","sommAfterMethod");

    printf( "GRRR\n" );
    Fierce_parent_SOMMBeforeAfter_sommAfterMethod(somSelf, ev, 
                                                  object, methodId, 
                                                  returnedvalue, 
                                                  ap);
}

